### Add user
POST http://127.0.0.1:3000/user/add HTTP/1.1
Authorization: hi
content-type: application/json

{
    "email": "326578901@qq.com",
    "username": "Xac",
    "password": "3313",
    "comment": null,
    "wechat": null,
    "phone_number": null,
    "group_id": 1,
    "avatar": null
}

###

GET http://127.0.0.1:3000/diary/list HTTP/1.1

###

POST http://127.0.0.1:3000/user/detail HTTP/1.1
content-type: application/json

###

{
    "uid": 123,
    "email": "1",
    "username": "123",
    "password": "123",
    "register_time": "2022-01-15T13:45:30Z",
    "last_visit_time": "2022-01-15T13:45:30Z",
    "group_id": 2,
    "diary_count": 0
}