//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.4

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "diary_category")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: u32,
    pub name: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::diary::Entity")]
    Diary,
}

impl Related<super::diary::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Diary.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
