//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.6

use super::sea_orm_active_enums::Mood;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "diary")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub did: u64,
    pub date: DateTime,
    pub title: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub content: Option<String>,
    pub temperature: Option<i8>,
    pub mood: Option<Mood>,
    pub weather: Option<u16>,
    pub date_create: DateTime,
    pub date_modify: DateTime,
    pub uid: u32,
    #[sea_orm(column_type = "Decimal(Some((9, 6)))", nullable)]
    pub longitude: Option<Decimal>,
    #[sea_orm(column_type = "Decimal(Some((9, 6)))", nullable)]
    pub latitude: Option<Decimal>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::diary_to_diary_tag::Entity")]
    DiaryToDiaryTag,
    #[sea_orm(
        belongs_to = "super::user::Entity",
        from = "Column::Uid",
        to = "super::user::Column::Uid",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    User,
}

impl Related<super::diary_to_diary_tag::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DiaryToDiaryTag.def()
    }
}

impl Related<super::user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::User.def()
    }
}

impl Related<super::diary_tag::Entity> for Entity {
    fn to() -> RelationDef {
        super::diary_to_diary_tag::Relation::DiaryTag.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::diary_to_diary_tag::Relation::Diary.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
