//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.6

pub use super::diary::Entity as Diary;
pub use super::diary_tag::Entity as DiaryTag;
pub use super::diary_to_diary_tag::Entity as DiaryToDiaryTag;
pub use super::user::Entity as User;
pub use super::user_group::Entity as UserGroup;
pub use super::user_to_diary_tag::Entity as UserToDiaryTag;
