//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.4

pub use super::diary::Entity as Diary;
pub use super::diary_category::Entity as DiaryCategory;
pub use super::user::Entity as User;
pub use super::user_group::Entity as UserGroup;
