//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.6

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "weather")]
pub enum Weather {
    #[sea_orm(string_value = "sunny")]
    Sunny,
    #[sea_orm(string_value = "cloudy")]
    Cloudy,
}
