//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.6

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "user")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub uid: u32,
    #[sea_orm(unique)]
    pub email: String,
    pub username: String,
    pub password: String,
    pub salt: String,
    pub register_time: DateTimeUtc,
    pub last_visit_time: DateTimeUtc,
    pub comment: Option<String>,
    pub wechat: Option<String>,
    pub phone_number: Option<String>,
    pub group_id: u32,
    pub diary_count: i32,
    pub avatar: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::diary::Entity")]
    Diary,
    #[sea_orm(
        belongs_to = "super::user_group::Entity",
        from = "Column::GroupId",
        to = "super::user_group::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    UserGroup,
    #[sea_orm(has_many = "super::user_to_diary_tag::Entity")]
    UserToDiaryTag,
}

impl Related<super::diary::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Diary.def()
    }
}

impl Related<super::user_group::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserGroup.def()
    }
}

impl Related<super::user_to_diary_tag::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserToDiaryTag.def()
    }
}

impl Related<super::diary_tag::Entity> for Entity {
    fn to() -> RelationDef {
        super::user_to_diary_tag::Relation::DiaryTag.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::user_to_diary_tag::Relation::User.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
